title: "Ai Blog ğŸ–¥ï¸"
email: "your-email@example.com"
description: "Personal blog about AI, technology, and more. by BSdeployment"
url: "https://BSdeployment.github.io" # ×”×—×œ×£ ×œ×›×ª×•×‘×ª ×©×œ×š
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
navigation: main

# ×ª×¦×•×’×ª ×‘×¨×™×¨×ª ××—×“×œ ×œ×¤×•×¡×˜×™×
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      enable_copy_code_button: true

search: true
lunr:
  search_within_pages: true
